name: build

on:
  push:
  pull_request:

env:
  CRDS_SERVER_URL: 'https://hst-crds.stsci.edu'
  DARK_PROGRAMS:
  # USE UTF8 ENCODING. SHOULD BE DEFAULT, BUT THIS IS INSURANCE AGAINST FUTURE CHANGES
  PYTHONIOENCODING: UTF8

#        - 
#        - 
#        - COSMO_FILES_SOURCE='/home/travis/build/spacetelescope/cosmo/tests/data'
#        - COSMO_SMS_SOURCE='/home/travis/build/spacetelescope/cosmo/tests/data'
#        - COSMO_OUTPUT='/home/travis/build/spacetelescope/cosmo/tests'
#        - COSMO_SMS_DB='/home/travis/build/spacetelescope/cosmo/tests/test.db'
#        - CRDS_PATH='/home/travis/build/spacetelescope/cosmo/tests/data/test_crds_cache'

jobs:
  build:
    name: build and install from source
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      MONITOR_CONFIG: ${{ github.workspace }}/tests/cosmoconfig_test.yaml

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: install conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.7'
        channels: http://ssb.stsci.edu/astroconda

    - name: install dependencies
      run: |
        conda install -c anaconda setuptools
        conda install stsci coverage sphinx
        pip install codecov

    - name: install from source
      run: pip install .

    - name: run tests
      run: coverage run -m pytest




############################

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
#addons:
#    apt:
#        packages:
#            - graphviz
#            - texlive-latex-extra
#            - dvipng

    # DOCUMENTATION DEPENDENCIES
#    - if [[ $SETUP_CMD == build_sphinx* ]]; then conda install numpy=$NUMPY_VERSION $CONDA_DOC_DEPS; fi


#after_success: codecov

